'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
'
Namespace AuthenticateUserWebService
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AuthenticateUserSoap", [Namespace]:="http://tempuri.org/WebService/AuthenticateUser")>  _
    Public Class AuthenticateUser
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/TimeReportWS/TimeReportWebServiceProjects_WebService/Authenticat"& _ 
"eUser.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebService/AuthenticateUser/GetUserGroups", RequestNamespace:="http://tempuri.org/WebService/AuthenticateUser", ResponseNamespace:="http://tempuri.org/WebService/AuthenticateUser", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUserGroups(ByVal domain As String, ByVal userName As String, ByVal password As String) As String
            Dim results() As Object = Me.Invoke("GetUserGroups", New Object() {domain, userName, password})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetUserGroups(ByVal domain As String, ByVal userName As String, ByVal password As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetUserGroups", New Object() {domain, userName, password}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetUserGroups(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
