'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dsOngoingReports
    Inherits DataSet
    
    Private tableOngoingReports As OngoingReportsDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("OngoingReports")) Is Nothing) Then
                Me.Tables.Add(New OngoingReportsDataTable(ds.Tables("OngoingReports")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property OngoingReports As OngoingReportsDataTable
        Get
            Return Me.tableOngoingReports
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dsOngoingReports = CType(MyBase.Clone,dsOngoingReports)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("OngoingReports")) Is Nothing) Then
            Me.Tables.Add(New OngoingReportsDataTable(ds.Tables("OngoingReports")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableOngoingReports = CType(Me.Tables("OngoingReports"),OngoingReportsDataTable)
        If (Not (Me.tableOngoingReports) Is Nothing) Then
            Me.tableOngoingReports.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dsOngoingReports"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/dsOngoingReports.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableOngoingReports = New OngoingReportsDataTable
        Me.Tables.Add(Me.tableOngoingReports)
    End Sub
    
    Private Function ShouldSerializeOngoingReports() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub OngoingReportsRowChangeEventHandler(ByVal sender As Object, ByVal e As OngoingReportsRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class OngoingReportsDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnWeekReportID As DataColumn
        
        Private columnStartDate As DataColumn
        
        Private columnEndDate As DataColumn
        
        Private columnWeekNumber As DataColumn
        
        Private columnExpectedHours As DataColumn
        
        Private columnUserReportsID As DataColumn
        
        Friend Sub New()
            MyBase.New("OngoingReports")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property WeekReportIDColumn As DataColumn
            Get
                Return Me.columnWeekReportID
            End Get
        End Property
        
        Friend ReadOnly Property StartDateColumn As DataColumn
            Get
                Return Me.columnStartDate
            End Get
        End Property
        
        Friend ReadOnly Property EndDateColumn As DataColumn
            Get
                Return Me.columnEndDate
            End Get
        End Property
        
        Friend ReadOnly Property WeekNumberColumn As DataColumn
            Get
                Return Me.columnWeekNumber
            End Get
        End Property
        
        Friend ReadOnly Property ExpectedHoursColumn As DataColumn
            Get
                Return Me.columnExpectedHours
            End Get
        End Property
        
        Friend ReadOnly Property UserReportsIDColumn As DataColumn
            Get
                Return Me.columnUserReportsID
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As OngoingReportsRow
            Get
                Return CType(Me.Rows(index),OngoingReportsRow)
            End Get
        End Property
        
        Public Event OngoingReportsRowChanged As OngoingReportsRowChangeEventHandler
        
        Public Event OngoingReportsRowChanging As OngoingReportsRowChangeEventHandler
        
        Public Event OngoingReportsRowDeleted As OngoingReportsRowChangeEventHandler
        
        Public Event OngoingReportsRowDeleting As OngoingReportsRowChangeEventHandler
        
        Public Overloads Sub AddOngoingReportsRow(ByVal row As OngoingReportsRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddOngoingReportsRow(ByVal WeekReportID As Long, ByVal StartDate As Date, ByVal EndDate As Date, ByVal WeekNumber As String, ByVal ExpectedHours As Integer, ByVal UserReportsID As Long) As OngoingReportsRow
            Dim rowOngoingReportsRow As OngoingReportsRow = CType(Me.NewRow,OngoingReportsRow)
            rowOngoingReportsRow.ItemArray = New Object() {WeekReportID, StartDate, EndDate, WeekNumber, ExpectedHours, UserReportsID}
            Me.Rows.Add(rowOngoingReportsRow)
            Return rowOngoingReportsRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As OngoingReportsDataTable = CType(MyBase.Clone,OngoingReportsDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New OngoingReportsDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnWeekReportID = Me.Columns("WeekReportID")
            Me.columnStartDate = Me.Columns("StartDate")
            Me.columnEndDate = Me.Columns("EndDate")
            Me.columnWeekNumber = Me.Columns("WeekNumber")
            Me.columnExpectedHours = Me.Columns("ExpectedHours")
            Me.columnUserReportsID = Me.Columns("UserReportsID")
        End Sub
        
        Private Sub InitClass()
            Me.columnWeekReportID = New DataColumn("WeekReportID", GetType(System.Int64), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnWeekReportID)
            Me.columnStartDate = New DataColumn("StartDate", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnStartDate)
            Me.columnEndDate = New DataColumn("EndDate", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnEndDate)
            Me.columnWeekNumber = New DataColumn("WeekNumber", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnWeekNumber)
            Me.columnExpectedHours = New DataColumn("ExpectedHours", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnExpectedHours)
            Me.columnUserReportsID = New DataColumn("UserReportsID", GetType(System.Int64), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnUserReportsID)
            Me.columnWeekReportID.AllowDBNull = false
            Me.columnStartDate.AllowDBNull = false
            Me.columnEndDate.AllowDBNull = false
            Me.columnWeekNumber.AllowDBNull = false
            Me.columnExpectedHours.AllowDBNull = false
            Me.columnUserReportsID.AllowDBNull = false
        End Sub
        
        Public Function NewOngoingReportsRow() As OngoingReportsRow
            Return CType(Me.NewRow,OngoingReportsRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New OngoingReportsRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(OngoingReportsRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.OngoingReportsRowChangedEvent) Is Nothing) Then
                RaiseEvent OngoingReportsRowChanged(Me, New OngoingReportsRowChangeEvent(CType(e.Row,OngoingReportsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.OngoingReportsRowChangingEvent) Is Nothing) Then
                RaiseEvent OngoingReportsRowChanging(Me, New OngoingReportsRowChangeEvent(CType(e.Row,OngoingReportsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.OngoingReportsRowDeletedEvent) Is Nothing) Then
                RaiseEvent OngoingReportsRowDeleted(Me, New OngoingReportsRowChangeEvent(CType(e.Row,OngoingReportsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.OngoingReportsRowDeletingEvent) Is Nothing) Then
                RaiseEvent OngoingReportsRowDeleting(Me, New OngoingReportsRowChangeEvent(CType(e.Row,OngoingReportsRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveOngoingReportsRow(ByVal row As OngoingReportsRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class OngoingReportsRow
        Inherits DataRow
        
        Private tableOngoingReports As OngoingReportsDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableOngoingReports = CType(Me.Table,OngoingReportsDataTable)
        End Sub
        
        Public Property WeekReportID As Long
            Get
                Return CType(Me(Me.tableOngoingReports.WeekReportIDColumn),Long)
            End Get
            Set
                Me(Me.tableOngoingReports.WeekReportIDColumn) = value
            End Set
        End Property
        
        Public Property StartDate As Date
            Get
                Return CType(Me(Me.tableOngoingReports.StartDateColumn),Date)
            End Get
            Set
                Me(Me.tableOngoingReports.StartDateColumn) = value
            End Set
        End Property
        
        Public Property EndDate As Date
            Get
                Return CType(Me(Me.tableOngoingReports.EndDateColumn),Date)
            End Get
            Set
                Me(Me.tableOngoingReports.EndDateColumn) = value
            End Set
        End Property
        
        Public Property WeekNumber As String
            Get
                Return CType(Me(Me.tableOngoingReports.WeekNumberColumn),String)
            End Get
            Set
                Me(Me.tableOngoingReports.WeekNumberColumn) = value
            End Set
        End Property
        
        Public Property ExpectedHours As Integer
            Get
                Return CType(Me(Me.tableOngoingReports.ExpectedHoursColumn),Integer)
            End Get
            Set
                Me(Me.tableOngoingReports.ExpectedHoursColumn) = value
            End Set
        End Property
        
        Public Property UserReportsID As Long
            Get
                Return CType(Me(Me.tableOngoingReports.UserReportsIDColumn),Long)
            End Get
            Set
                Me(Me.tableOngoingReports.UserReportsIDColumn) = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class OngoingReportsRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As OngoingReportsRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As OngoingReportsRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As OngoingReportsRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
