'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dsProjects
    Inherits DataSet
    
    Private tableProjects As ProjectsDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("Projects")) Is Nothing) Then
                Me.Tables.Add(New ProjectsDataTable(ds.Tables("Projects")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property Projects As ProjectsDataTable
        Get
            Return Me.tableProjects
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dsProjects = CType(MyBase.Clone,dsProjects)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("Projects")) Is Nothing) Then
            Me.Tables.Add(New ProjectsDataTable(ds.Tables("Projects")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableProjects = CType(Me.Tables("Projects"),ProjectsDataTable)
        If (Not (Me.tableProjects) Is Nothing) Then
            Me.tableProjects.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dsProjects"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/dsProjects.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableProjects = New ProjectsDataTable
        Me.Tables.Add(Me.tableProjects)
    End Sub
    
    Private Function ShouldSerializeProjects() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub ProjectsRowChangeEventHandler(ByVal sender As Object, ByVal e As ProjectsRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class ProjectsDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnUserProjectID As DataColumn
        
        Private columnProjectID As DataColumn
        
        Private columnRootProjectID As DataColumn
        
        Private columnUserID As DataColumn
        
        Private columnProjectName As DataColumn
        
        Private columnDescription As DataColumn
        
        Friend Sub New()
            MyBase.New("Projects")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property UserProjectIDColumn As DataColumn
            Get
                Return Me.columnUserProjectID
            End Get
        End Property
        
        Friend ReadOnly Property ProjectIDColumn As DataColumn
            Get
                Return Me.columnProjectID
            End Get
        End Property
        
        Friend ReadOnly Property RootProjectIDColumn As DataColumn
            Get
                Return Me.columnRootProjectID
            End Get
        End Property
        
        Friend ReadOnly Property UserIDColumn As DataColumn
            Get
                Return Me.columnUserID
            End Get
        End Property
        
        Friend ReadOnly Property ProjectNameColumn As DataColumn
            Get
                Return Me.columnProjectName
            End Get
        End Property
        
        Friend ReadOnly Property DescriptionColumn As DataColumn
            Get
                Return Me.columnDescription
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As ProjectsRow
            Get
                Return CType(Me.Rows(index),ProjectsRow)
            End Get
        End Property
        
        Public Event ProjectsRowChanged As ProjectsRowChangeEventHandler
        
        Public Event ProjectsRowChanging As ProjectsRowChangeEventHandler
        
        Public Event ProjectsRowDeleted As ProjectsRowChangeEventHandler
        
        Public Event ProjectsRowDeleting As ProjectsRowChangeEventHandler
        
        Public Overloads Sub AddProjectsRow(ByVal row As ProjectsRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddProjectsRow(ByVal UserProjectID As Long, ByVal ProjectID As Long, ByVal RootProjectID As Long, ByVal UserID As Long, ByVal ProjectName As String, ByVal Description As String) As ProjectsRow
            Dim rowProjectsRow As ProjectsRow = CType(Me.NewRow,ProjectsRow)
            rowProjectsRow.ItemArray = New Object() {UserProjectID, ProjectID, RootProjectID, UserID, ProjectName, Description}
            Me.Rows.Add(rowProjectsRow)
            Return rowProjectsRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As ProjectsDataTable = CType(MyBase.Clone,ProjectsDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New ProjectsDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnUserProjectID = Me.Columns("UserProjectID")
            Me.columnProjectID = Me.Columns("ProjectID")
            Me.columnRootProjectID = Me.Columns("RootProjectID")
            Me.columnUserID = Me.Columns("UserID")
            Me.columnProjectName = Me.Columns("ProjectName")
            Me.columnDescription = Me.Columns("ProjectDesription")
        End Sub
        
        Private Sub InitClass()
            Me.columnUserProjectID = New DataColumn("UserProjectID", GetType(System.Int64), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnUserProjectID)
            Me.columnProjectID = New DataColumn("ProjectID", GetType(System.Int64), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnProjectID)
            Me.columnRootProjectID = New DataColumn("RootProjectID", GetType(System.Int64), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnRootProjectID)
            Me.columnUserID = New DataColumn("UserID", GetType(System.Int64), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnUserID)
            Me.columnProjectName = New DataColumn("ProjectName", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnProjectName)
            Me.columnDescription = New DataColumn("ProjectDesription", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDescription)
            Me.columnUserProjectID.AllowDBNull = false
            Me.columnProjectID.AllowDBNull = false
            Me.columnRootProjectID.AllowDBNull = false
            Me.columnUserID.AllowDBNull = false
            Me.columnProjectName.AllowDBNull = false
        End Sub
        
        Public Function NewProjectsRow() As ProjectsRow
            Return CType(Me.NewRow,ProjectsRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New ProjectsRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(ProjectsRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.ProjectsRowChangedEvent) Is Nothing) Then
                RaiseEvent ProjectsRowChanged(Me, New ProjectsRowChangeEvent(CType(e.Row,ProjectsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.ProjectsRowChangingEvent) Is Nothing) Then
                RaiseEvent ProjectsRowChanging(Me, New ProjectsRowChangeEvent(CType(e.Row,ProjectsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.ProjectsRowDeletedEvent) Is Nothing) Then
                RaiseEvent ProjectsRowDeleted(Me, New ProjectsRowChangeEvent(CType(e.Row,ProjectsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.ProjectsRowDeletingEvent) Is Nothing) Then
                RaiseEvent ProjectsRowDeleting(Me, New ProjectsRowChangeEvent(CType(e.Row,ProjectsRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveProjectsRow(ByVal row As ProjectsRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class ProjectsRow
        Inherits DataRow
        
        Private tableProjects As ProjectsDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableProjects = CType(Me.Table,ProjectsDataTable)
        End Sub
        
        Public Property UserProjectID As Long
            Get
                Return CType(Me(Me.tableProjects.UserProjectIDColumn),Long)
            End Get
            Set
                Me(Me.tableProjects.UserProjectIDColumn) = value
            End Set
        End Property
        
        Public Property ProjectID As Long
            Get
                Return CType(Me(Me.tableProjects.ProjectIDColumn),Long)
            End Get
            Set
                Me(Me.tableProjects.ProjectIDColumn) = value
            End Set
        End Property
        
        Public Property RootProjectID As Long
            Get
                Return CType(Me(Me.tableProjects.RootProjectIDColumn),Long)
            End Get
            Set
                Me(Me.tableProjects.RootProjectIDColumn) = value
            End Set
        End Property
        
        Public Property UserID As Long
            Get
                Return CType(Me(Me.tableProjects.UserIDColumn),Long)
            End Get
            Set
                Me(Me.tableProjects.UserIDColumn) = value
            End Set
        End Property
        
        Public Property ProjectName As String
            Get
                Return CType(Me(Me.tableProjects.ProjectNameColumn),String)
            End Get
            Set
                Me(Me.tableProjects.ProjectNameColumn) = value
            End Set
        End Property
        
        Public Property Description As String
            Get
                Try 
                    Return CType(Me(Me.tableProjects.DescriptionColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableProjects.DescriptionColumn) = value
            End Set
        End Property
        
        Public Function IsDescriptionNull() As Boolean
            Return Me.IsNull(Me.tableProjects.DescriptionColumn)
        End Function
        
        Public Sub SetDescriptionNull()
            Me(Me.tableProjects.DescriptionColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class ProjectsRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As ProjectsRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As ProjectsRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As ProjectsRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
